# Generated by Django 4.2.5 on 2023-11-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='img',
            field=models.ImageField(blank=True, upload_to='chatimg/%y'),
        ),
    ]
