# Generated by Django 4.2.5 on 2023-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, max_length=99999999999999999999999999999),
        ),
    ]
